// Package auth generates authentication middleware.
package auth

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/fisayoafolayan/kiln/internal/generator/genopt"
)

// Generator writes generated/auth/middleware.go — a write-once middleware
type Generator struct {
	opts genopt.Options
	tmpl *template.Template
}

// New returns a Generator ready to run.
func New(opts genopt.Options) (*Generator, error) {
	strategy := opts.Config.Auth.Strategy
	src, ok := strategyTemplates[strategy]
	if !ok {
		return nil, fmt.Errorf("unknown auth strategy: %q", strategy)
	}
	tmpl, err := template.New("auth").Parse(src)
	if err != nil {
		return nil, fmt.Errorf("parsing auth template: %w", err)
	}
	return &Generator{opts: opts, tmpl: tmpl}, nil
}

type templateData struct {
	OutputPkg string
	Header    string
}

// Run generates the middleware file if it doesn't already exist.
func (g *Generator) Run() ([]string, error) {
	outDir := filepath.Join(g.opts.Config.Output.Dir, "auth")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return nil, fmt.Errorf("creating auth dir: %w", err)
	}

	path := filepath.Join(outDir, "middleware.go")

	// Write-once: don't overwrite existing middleware.
	if _, err := os.Stat(path); err == nil {
		return []string{path + " (write-once, skipped)"}, nil
	}

	data := templateData{
		OutputPkg: "auth",
		Header:    g.opts.Config.Auth.Header,
	}
	if err := genopt.ExecuteAndWrite(g.tmpl, data, path); err != nil {
		return nil, err
	}

	// If main.go already exists, it won't be regenerated with the auth import.
	mainPath := filepath.Join("cmd", "server", "main.go")
	if _, err := os.Stat(mainPath); err == nil {
		fmt.Fprintf(os.Stderr, `
  ⚠ Auth middleware generated, but %s already exists (write-once).
  Add the following to your main.go manually:

    import "%s/auth"

    // After RegisterRoutes:
    handler := auth.Middleware(mux)
    http.ListenAndServe(addr, handler)

`, mainPath, g.opts.ImportPath)
	}

	return []string{path}, nil
}

// Diff returns the list of files that would be written.
func (g *Generator) Diff() []string {
	path := filepath.Join(g.opts.Config.Output.Dir, "auth", "middleware.go")
	return []string{path + " (write-once)"}
}

// strategyTemplates maps auth.strategy → Go template source.
var strategyTemplates = map[string]string{
	"jwt":     jwtTemplate,
	"api_key": apiKeyTemplate,
}

const jwtTemplate = `// Code generated by kiln. YOU OWN THIS FILE.
//
// This middleware validates JWT tokens from the {{.Header}} header.
// Replace the TODO with your JWT validation logic (e.g. using
// github.com/golang-jwt/jwt/v5 or your auth provider's SDK).
package {{.OutputPkg}}

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

// claimsKey is the context key for storing validated claims.
type ctxKey string

const ClaimsKey ctxKey = "auth_claims"

// Claims represents the decoded JWT claims.
// Extend this struct with your own fields.
type Claims struct {
	Subject string
	Email   string
	Roles   []string
}

// Middleware returns an HTTP middleware that validates JWT bearer tokens.
// Unauthenticated requests receive a 401 response.
func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		header := r.Header.Get("{{.Header}}")
		if header == "" {
			writeAuthError(w, http.StatusUnauthorized, "missing authorization header")
			return
		}

		token := strings.TrimPrefix(header, "Bearer ")
		if token == header {
			// No "Bearer " prefix found.
			writeAuthError(w, http.StatusUnauthorized, "invalid authorization format, expected: Bearer <token>")
			return
		}

		claims, err := validateToken(token)
		if err != nil {
			writeAuthError(w, http.StatusUnauthorized, "invalid token")
			return
		}

		ctx := context.WithValue(r.Context(), ClaimsKey, claims)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// validateToken validates a JWT token string and returns the decoded claims.
// Replace this function body with your actual validation logic.
func validateToken(token string) (*Claims, error) {
	// SECURITY: This placeholder REJECTS all tokens.
	// You must implement real validation before your API will accept requests.
	//
	// Example using golang-jwt:
	//
	//   parsed, err := jwt.Parse(token, func(t *jwt.Token) (any, error) {
	//       return []byte(os.Getenv("JWT_SECRET")), nil
	//   })
	//   if err != nil || !parsed.Valid {
	//       return nil, fmt.Errorf("invalid token")
	//   }
	//   mapClaims := parsed.Claims.(jwt.MapClaims)
	//   return &Claims{Subject: mapClaims["sub"].(string)}, nil
	//
	return nil, fmt.Errorf("jwt validation not implemented — edit generated/auth/middleware.go")
}

// ClaimsFrom extracts the validated claims from the request context.
// Returns nil if the request was not authenticated.
func ClaimsFrom(ctx context.Context) *Claims {
	c, _ := ctx.Value(ClaimsKey).(*Claims)
	return c
}

func writeAuthError(w http.ResponseWriter, status int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(map[string]string{"error": msg})
}
`

const apiKeyTemplate = `// Code generated by kiln. YOU OWN THIS FILE.
//
// This middleware validates API keys from the {{.Header}} header.
// Replace the TODO with your key validation logic (e.g. database
// lookup, environment variable check, or external service call).
package {{.OutputPkg}}

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// apiKeyKey is the context key for storing the validated API key identity.
type ctxKey string

const APIKeyIdentityKey ctxKey = "api_key_identity"

// Identity represents the authenticated API key holder.
// Extend this struct with your own fields.
type Identity struct {
	KeyID string
	Name  string
	Roles []string
}

// Middleware returns an HTTP middleware that validates API keys.
// Unauthenticated requests receive a 401 response.
func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		key := r.Header.Get("{{.Header}}")
		if key == "" {
			writeAuthError(w, http.StatusUnauthorized, "missing api key")
			return
		}

		identity, err := validateAPIKey(key)
		if err != nil {
			writeAuthError(w, http.StatusUnauthorized, "invalid api key")
			return
		}

		ctx := context.WithValue(r.Context(), APIKeyIdentityKey, identity)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// validateAPIKey validates an API key and returns the identity it belongs to.
// Replace this function body with your actual validation logic.
func validateAPIKey(key string) (*Identity, error) {
	// SECURITY: This placeholder REJECTS all keys.
	// You must implement real validation before your API will accept requests.
	//
	// Example:
	//
	//   identity, err := db.LookupAPIKey(ctx, key)
	//   if err != nil {
	//       return nil, fmt.Errorf("invalid api key")
	//   }
	//   return &Identity{KeyID: identity.ID, Name: identity.Name}, nil
	//
	return nil, fmt.Errorf("api key validation not implemented — edit generated/auth/middleware.go")
}

// IdentityFrom extracts the validated identity from the request context.
// Returns nil if the request was not authenticated.
func IdentityFrom(ctx context.Context) *Identity {
	id, _ := ctx.Value(APIKeyIdentityKey).(*Identity)
	return id
}

func writeAuthError(w http.ResponseWriter, status int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(map[string]string{"error": msg})
}
`
