version: 2

builds:
  - main: ./cmd/kiln
    binary: kiln
    ldflags:
      - -s -w
      - -X github.com/fisayoafolayan/kiln/internal/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "kiln_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: kiln
    binaries:
      - kiln
    repository:
      owner: fisayoafolayan
      name: homebrew-kiln
      token: "{{ .Env.BREW_TOKEN }}"
    homepage: https://github.com/fisayoafolayan/kiln
    description: "Schema-first API compiler for Go"
    license: MIT

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
