// Package mainfile generates a write-once main.go that wires up the
// generated stores, handlers, and router into a runnable HTTP server.
package mainfile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/fisayoafolayan/kiln/internal/generator/genopt"
	"github.com/fisayoafolayan/kiln/internal/ir"
)

// Generator writes cmd/server/main.go - write-once, never overwritten.
// Only runs when ModulePath is set (skipped during unit tests).
type Generator struct {
	opts genopt.Options
	tmpl *template.Template
}

// New returns a Generator ready to run.
func New(opts genopt.Options) (*Generator, error) {
	tmpl, err := template.New("main").Funcs(template.FuncMap{
		"isChi": func(f string) bool { return f == "chi" },
	}).Parse(mainTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing main template: %w", err)
	}
	return &Generator{opts: opts, tmpl: tmpl}, nil
}

// Run generates cmd/server/main.go relative to the current working directory.
// Skipped when ModulePath is empty - this is the unit test guard.
func (g *Generator) Run() ([]string, error) {
	if g.opts.ModulePath == "" {
		return nil, nil
	}

	path := filepath.Join("cmd", "server", "main.go")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return nil, fmt.Errorf("creating cmd/server dir: %w", err)
	}

	// Write-once - never overwrite an existing main.go
	if _, err := os.Stat(path); err == nil {
		return nil, nil
	}

	data := g.templateData()

	if _, err := genopt.ExecuteAndWrite(g.tmpl, data, path, true); err != nil {
		return nil, err
	}

	return []string{path}, nil
}

// Diff returns the file that would be written without writing it.
func (g *Generator) Diff() []string {
	if g.opts.ModulePath == "" {
		return nil
	}
	path := filepath.Join("cmd", "server", "main.go")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return []string{path + " (write-once)"}
}

type templateData struct {
	ImportPath   string
	BasePath     string
	Port         string
	DriverImport string
	DriverName   string
	Framework    string
	Tables       []*ir.Table
	AuthEnabled  bool
}

func (g *Generator) templateData() templateData {
	var tables []*ir.Table
	for _, t := range g.opts.Schema.Tables {
		if g.opts.Config.ShouldGenerateTable(t.Name) {
			tables = append(tables, t)
		}
	}
	outDir := strings.TrimPrefix(g.opts.Config.Output.Dir, "./")
	return templateData{
		ImportPath:   g.opts.ModulePath + "/" + outDir,
		BasePath:     g.opts.Config.API.BasePath,
		Port:         "8080",
		DriverImport: g.opts.Dialect.DriverImport,
		DriverName:   g.opts.Dialect.DriverName,
		Framework:    g.opts.Config.API.Framework,
		Tables:       tables,
		AuthEnabled:  g.opts.Config.Auth.Strategy != "none",
	}
}

const mainTemplate = `// Generated by kiln. THIS FILE IS YOURS - kiln will never overwrite it.
// Run: go run cmd/server/main.go

package main

import (
	"database/sql"
	"log"
	"net/http"
	"os"

{{if isChi .Framework}}	"github.com/go-chi/chi/v5"
{{end}}	"github.com/stephenafamo/bob"
	_ "{{.DriverImport}}"
	"{{.ImportPath}}"
{{if .AuthEnabled}}	"{{.ImportPath}}/auth"
{{end}}	"{{.ImportPath}}/handlers"
	"{{.ImportPath}}/store"
)

func main() {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		log.Fatal("DATABASE_URL is required")
	}

	sqlDB, err := sql.Open("{{.DriverName}}", dsn)
	if err != nil {
		log.Fatalf("failed to open database: %v", err)
	}
	defer sqlDB.Close()

	db := bob.NewDB(sqlDB)

{{range .Tables}}	{{.Name}}Store := store.New{{.GoName}}Store(db)
{{end}}
{{range .Tables}}	{{.Name}}Handler := handlers.New{{.GoName}}Handler({{.Name}}Store)
{{end}}
{{if isChi .Framework}}	r := chi.NewRouter()
{{if .AuthEnabled}}	r.Use(auth.Middleware)
{{end}}	generated.RegisterRoutes(r,
{{range .Tables}}		{{.Name}}Handler,
{{end}}	)
{{else}}	mux := http.NewServeMux()
	generated.RegisterRoutes(mux,
{{range .Tables}}		{{.Name}}Handler,
{{end}}	)
{{end}}
	addr := ":{{.Port}}"
	log.Printf("listening on http://localhost%s", addr)
	log.Fatal(http.ListenAndServe(addr, {{if isChi .Framework}}r{{else if .AuthEnabled}}auth.Middleware(mux){{else}}mux{{end}}))
}
`
