// Package mainfile generates a write-once main.go that wires up the
// generated stores, handlers, and router into a runnable HTTP server.
package mainfile

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/fisayoafolayan/kiln/internal/generator/genopt"
	"github.com/fisayoafolayan/kiln/internal/ir"
)

// Generator writes cmd/server/main.go — write-once, never overwritten.
// Only runs when ModulePath is set (skipped during unit tests).
type Generator struct {
	opts genopt.Options
	tmpl *template.Template
}

// New returns a Generator ready to run.
func New(opts genopt.Options) (*Generator, error) {
	tmpl, err := template.New("main").Parse(mainTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing main template: %w", err)
	}
	return &Generator{opts: opts, tmpl: tmpl}, nil
}

// Run generates cmd/server/main.go relative to the current working directory.
// Skipped when ModulePath is empty — this is the unit test guard.
func (g *Generator) Run() ([]string, error) {
	if g.opts.ModulePath == "" {
		return nil, nil
	}

	path := filepath.Join("cmd", "server", "main.go")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return nil, fmt.Errorf("creating cmd/server dir: %w", err)
	}

	// Write-once — never overwrite an existing main.go
	if _, err := os.Stat(path); err == nil {
		return nil, nil
	}

	data := g.templateData()

	var buf bytes.Buffer
	if err := g.tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing main template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		formatted = buf.Bytes()
	}

	if err := os.WriteFile(path, formatted, 0644); err != nil {
		return nil, fmt.Errorf("writing cmd/server/main.go: %w", err)
	}

	return []string{path}, nil
}

// Diff returns the file that would be written without writing it.
func (g *Generator) Diff() []string {
	if g.opts.ModulePath == "" {
		return nil
	}
	path := filepath.Join("cmd", "server", "main.go")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return []string{path + " (write-once)"}
}

type templateData struct {
	ImportPath   string
	BasePath     string
	Port         string
	DriverImport string
	DriverName   string
	Tables       []*ir.Table
}

func (g *Generator) templateData() templateData {
	var tables []*ir.Table
	for _, t := range g.opts.Schema.Tables {
		if g.opts.Config.ShouldGenerateTable(t.Name) {
			tables = append(tables, t)
		}
	}
	outDir := strings.TrimPrefix(g.opts.Config.Output.Dir, "./")
	return templateData{
		ImportPath:   g.opts.ModulePath + "/" + outDir,
		BasePath:     g.opts.Config.API.BasePath,
		Port:         "8080",
		DriverImport: g.opts.Dialect.DriverImport,
		DriverName:   g.opts.Dialect.DriverName,
		Tables:       tables,
	}
}

const mainTemplate = `// Generated by kiln. THIS FILE IS YOURS — kiln will never overwrite it.
// Run: go run cmd/server/main.go

package main

import (
	"database/sql"
	"log"
	"net/http"
	"os"

	"github.com/stephenafamo/bob"
	_ "{{.DriverImport}}"
	"{{.ImportPath}}"
	"{{.ImportPath}}/handlers"
	"{{.ImportPath}}/store"
)

func main() {
	// 1. Connect to the database.
	//    Set DATABASE_URL or replace the DSN string directly.
	dsn := mustEnv("DATABASE_URL")
	sqlDB, err := sql.Open("{{.DriverName}}", dsn)
	if err != nil {
		log.Fatalf("failed to open database: %v", err)
	}
	defer sqlDB.Close()

	if err := sqlDB.Ping(); err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}

	db := bob.NewDB(sqlDB)

	// 2. Wire up stores.
{{range .Tables}}	{{.Name}}Store := store.New{{.GoName}}Store(db)
{{end}}
	// 3. Wire up handlers.
{{range .Tables}}	{{.Name}}Handler := handlers.New{{.GoName}}Handler({{.Name}}Store)
{{end}}
	// 4. Register routes.
	mux := http.NewServeMux()
	generated.RegisterRoutes(mux,
{{range .Tables}}		{{.Name}}Handler,
{{end}}	)

	// 5. Start the server.
	addr := ":{{.Port}}"
	log.Printf("kiln server listening on http://localhost%s", addr)
	log.Printf("API base path: {{.BasePath}}")
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

// mustEnv returns the value of an environment variable or exits if not set.
func mustEnv(key string) string {
	val := os.Getenv(key)
	if val == "" {
		log.Fatalf("environment variable %q is required", key)
	}
	return val
}
`
