// Package types generates request/response structs for each table.
package types

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"

	"github.com/fisayoafolayan/kiln/internal/config"
	"github.com/fisayoafolayan/kiln/internal/generator/genopt"
	"github.com/fisayoafolayan/kiln/internal/ir"
)

// Generator writes generated/types/<table>.go for each table.
type Generator struct {
	opts genopt.Options
	tmpl *template.Template
}

// New returns a Generator ready to run.
func New(opts genopt.Options) (*Generator, error) {
	tmpl, err := template.New("types").Funcs(funcMap()).Parse(typesTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing types template: %w", err)
	}
	return &Generator{opts: opts, tmpl: tmpl}, nil
}

// Run generates a types file for every table in the schema.
func (g *Generator) Run() ([]string, error) {
	outDir := filepath.Join(g.opts.Config.Output.Dir, "types")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return nil, fmt.Errorf("creating output dir %q: %w", outDir, err)
	}

	var written []string
	for _, t := range g.opts.Schema.Tables {
		if !g.opts.Config.ShouldGenerateTable(t.Name) {
			continue
		}
		if t.PrimaryKey == nil {
			continue
		}
		path, err := g.writeTable(t, outDir)
		if err != nil {
			return nil, fmt.Errorf("generating types for %q: %w", t.Name, err)
		}
		written = append(written, path)
	}
	return written, nil
}

// Diff returns the list of files that would be written without writing them.
func (g *Generator) Diff() []string {
	outDir := filepath.Join(g.opts.Config.Output.Dir, "types")
	var files []string
	for _, t := range g.opts.Schema.Tables {
		if !g.opts.Config.ShouldGenerateTable(t.Name) {
			continue
		}
		files = append(files, filepath.Join(outDir, t.Name+".go"))
	}
	return files
}

func (g *Generator) writeTable(t *ir.Table, outDir string) (string, error) {
	override := g.opts.Config.OverrideFor(t.Name)

	data := templateData{
		Package:  g.opts.Config.Output.Package,
		Table:    t,
		Override: override,
		Imports:  resolveImports(t, override),
	}

	var buf bytes.Buffer
	if err := g.tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	// Run gofmt on the output — generated code must be properly formatted.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write the raw output so the error is debuggable.
		formatted = buf.Bytes()
	}

	path := filepath.Join(outDir, t.Name+".go")
	if err := os.WriteFile(path, formatted, 0644); err != nil {
		return "", fmt.Errorf("writing %q: %w", path, err)
	}
	return path, nil
}

// templateData is the data passed to the types template.
type templateData struct {
	Package  string
	Table    *ir.Table
	Override config.TableOverride
	Imports  []string
}

// resolveImports returns the import paths needed for this table's types file.
func resolveImports(t *ir.Table, override config.TableOverride) []string {
	seen := map[string]bool{}
	var imports []string

	add := func(pkg string) {
		if pkg != "" && !seen[pkg] {
			seen[pkg] = true
			imports = append(imports, pkg)
		}
	}

	for _, c := range t.Columns {
		if override.IsFieldHidden(c.Name) {
			continue
		}
		add(c.GoType.Package)
	}
	return imports
}

// funcMap returns the template helper functions.
func funcMap() template.FuncMap {
	return template.FuncMap{
		// isVisible returns true if a column should appear in response structs.
		"isVisible": func(c *ir.Column, o config.TableOverride) bool {
			return !o.IsFieldHidden(c.Name)
		},
		// isWritable returns true if a column should appear in Create/Update structs.
		"isWritable": func(c *ir.Column, o config.TableOverride) bool {
			return !c.IsReadOnly() && !o.IsFieldHidden(c.Name) && !o.IsFieldReadonly(c.Name)
		},
		// isCreatable returns true if a column should appear in CreateRequest.
		// Excludes fields that have DB defaults (they're optional on create).
		"isCreatable": func(c *ir.Column, o config.TableOverride) bool {
			return !c.IsReadOnly() && !o.IsFieldHidden(c.Name) && !o.IsFieldReadonly(c.Name)
		},
		// validationTag returns the validate struct tag for a column.
		"validationTag": func(c *ir.Column) string {
			return c.ValidationTag()
		},
		// isOperationEnabled returns true if the operation is not disabled.
		"isOperationEnabled": func(op string, o config.TableOverride) bool {
			return !o.IsOperationDisabled(op)
		},
	}
}

// typesTemplate is the Go template for a types file.
// Produces: response struct, create request, update request, list response.
const typesTemplate = `// Code generated by kiln. DO NOT EDIT.
// kiln:table={{.Table.Name}} kiln:checksum=__CHECKSUM__

package types

{{if .Imports}}
import (
{{range .Imports}}	{{printf "%q" .}}
{{end}})
{{end}}

// {{.Table.GoName}} is the response type for a {{.Table.Name}} record.
type {{.Table.GoName}} struct {
{{range .Table.Columns}}{{if isVisible . $.Override}}	{{.GoName}} {{.GoType.String}} ` + "`" + `json:"{{.JSONName}}{{if .Nullable}},omitempty{{end}}"` + "`" + `
{{end}}{{end}}}

{{if isOperationEnabled "create" .Override}}
// Create{{.Table.GoName}}Request is the request body for POST /{{.Table.Endpoint}}.
type Create{{.Table.GoName}}Request struct {
{{range .Table.Columns}}{{if isCreatable . $.Override}}	{{.GoName}} {{if .Nullable}}*{{end}}{{.GoType.Name}} ` + "`" + `json:"{{.JSONName}}"{{with validationTag .}} validate:"{{.}}"{{end}}` + "`" + `
{{end}}{{end}}}
{{end}}

{{if isOperationEnabled "update" .Override}}
// Update{{.Table.GoName}}Request is the request body for PATCH /{{.Table.Endpoint}}/:id.
// All fields are optional — only non-nil fields are updated.
type Update{{.Table.GoName}}Request struct {
{{range .Table.Columns}}{{if isWritable . $.Override}}	{{.GoName}} *{{.GoType.Name}} ` + "`" + `json:"{{.JSONName}},omitempty"{{with validationTag .}} validate:"{{.}}"{{end}}` + "`" + `
{{end}}{{end}}}
{{end}}

{{if isOperationEnabled "list" .Override}}
// List{{.Table.GoNamePlural}}Response is the response body for GET /{{.Table.Endpoint}}.
type List{{.Table.GoNamePlural}}Response struct {
	Data     []{{.Table.GoName}} ` + "`" + `json:"data"` + "`" + `
	Total    int                  ` + "`" + `json:"total"` + "`" + `
	Page     int                  ` + "`" + `json:"page"` + "`" + `
	PageSize int                  ` + "`" + `json:"page_size"` + "`" + `
}
{{end}}
`
