package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func initCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Create a kiln.yaml config file interactively",
		RunE: func(cmd *cobra.Command, args []string) error {
			if _, err := os.Stat(cfgFile); err == nil {
				if !confirm(fmt.Sprintf("%q already exists. Overwrite?", cfgFile)) {
					fmt.Println("Aborted.")
					return nil
				}
			}

			r := bufio.NewReader(os.Stdin)

			fmt.Println(`
┌─────────────────────────────────────────┐
│  kiln - schema-driven Go API generator  │
└─────────────────────────────────────────┘

kiln reads your database schema and generates a complete,
idiomatic Go API - models, store, handlers, router, and OpenAPI spec.

Under the hood, kiln uses bob (github.com/stephenafamo/bob) to
introspect your database. You don't need to know how bob works -
kiln handles it for you.

Let's get started.`)

			driver := prompt(r, "Database driver (postgres/mysql/sqlite)", "postgres")
			dsn := prompt(r, "Database DSN (or leave blank to use an env var)", "")
			dsnEnv := ""
			if dsn == "" {
				dsnEnv = prompt(r, "Environment variable name for DSN", "DATABASE_URL")
			}
			outDir := prompt(r, "Output directory", "./generated")
			basePath := prompt(r, "API base path", "/api/v1")

			// resolvedDSN is used in bobgen.yaml.
			// If using an env var, embed the env var reference.
			resolvedDSN := dsn
			if resolvedDSN == "" {
				resolvedDSN = fmt.Sprintf("${%s}", dsnEnv)
			}

			modelsDir := "./models"

			// --- Write kiln.yaml ---
			dsnField := ""
			if dsn != "" {
				dsnField = fmt.Sprintf("  dsn: %q", dsn)
			} else {
				dsnField = fmt.Sprintf("  dsn_env: %q", dsnEnv)
			}

			kilnYAML := fmt.Sprintf(`version: 1

database:
  driver: %q
%s

output:
  dir: %q
  package: generated

api:
  base_path: %q
  framework: stdlib

bob:
  enabled: true
  models_dir: %q

generate:
  models: true
  store: true
  handlers: true
  router: true
  openapi: true

openapi:
  enabled: true
  output: ./docs/openapi.yaml
  title: My API
  version: 1.0.0

tables:
  exclude:
    - schema_migrations
`, driver, dsnField, outDir, basePath, modelsDir)

			if err := os.WriteFile(cfgFile, []byte(kilnYAML), 0644); err != nil {
				return fmt.Errorf("writing %s: %w", cfgFile, err)
			}
			fmt.Printf("  ✓ Created %s\n", cfgFile)

			// --- Write bobgen.yaml ---
			// kiln generates this automatically so the developer never
			// needs to know it exists.
			bobConfig := buildBobConfig(driver, resolvedDSN, modelsDir)
			if err := os.WriteFile("bobgen.yaml", []byte(bobConfig), 0644); err != nil {
				return fmt.Errorf("writing bobgen.yaml: %w", err)
			}
			fmt.Println("  ✓ Created bobgen.yaml (used internally by kiln)")

			fmt.Println(`
Setup complete. Run:

  kiln generate`)
			return nil
		},
	}
}

// buildBobConfig generates a bobgen.yaml config for the given driver and DSN.
// outputDir should be the path where bob writes its models - must match
// the models_dir in kiln.yaml.
func buildBobConfig(driver, dsn, outputDir string) string {
	// Strip the "bobgen-" prefix to get the bob config section name.
	gen := strings.TrimPrefix(bobGenBinary(driver), "bobgen-")
	return fmt.Sprintf(`# Generated by kiln. You don't need to edit this file manually.
# kiln uses bobgen-%s to introspect your database schema.

%s:
  dsn: %q
  output: %q
  pkg_name: "models"
`, gen, gen, dsn, outputDir)
}
