package bob_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/fisayoafolayan/kiln/internal/ir"
	"github.com/fisayoafolayan/kiln/internal/parser/bob"
)

// writeModel writes a bob-style .bob.go file to a temp dir.
func writeModel(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
		t.Fatalf("writing model file: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Fixtures — minimal bob-style model files
// ─────────────────────────────────────────────────────────────────────────────

const usersModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import (
	"time"
	"github.com/aarondl/opt/null"
	"github.com/gofrs/uuid/v5"
)

// User is an object representing the database table.
type User struct {
	ID        uuid.UUID        ` + "`" + `db:"id,pk" ` + "`" + `
	Email     string           ` + "`" + `db:"email" ` + "`" + `
	Name      string           ` + "`" + `db:"name" ` + "`" + `
	Bio       null.Val[string] ` + "`" + `db:"bio" ` + "`" + `
	Role      string           ` + "`" + `db:"role" ` + "`" + `
	CreatedAt time.Time        ` + "`" + `db:"created_at" ` + "`" + `
	UpdatedAt time.Time        ` + "`" + `db:"updated_at" ` + "`" + `
	R userR ` + "`" + `db:"-" ` + "`" + `
}

type UserSlice []*User
type userR struct{}
`

const postsModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import (
	"time"
	"github.com/aarondl/opt/null"
	"github.com/gofrs/uuid/v5"
)

// Post is an object representing the database table.
type Post struct {
	ID          uuid.UUID        ` + "`" + `db:"id,pk" ` + "`" + `
	UserID      uuid.UUID        ` + "`" + `db:"user_id" ` + "`" + `
	Title       string           ` + "`" + `db:"title" ` + "`" + `
	Body        string           ` + "`" + `db:"body" ` + "`" + `
	Status      string           ` + "`" + `db:"status" ` + "`" + `
	PublishedAt null.Val[time.Time] ` + "`" + `db:"published_at" ` + "`" + `
	CreatedAt   time.Time        ` + "`" + `db:"created_at" ` + "`" + `
	UpdatedAt   time.Time        ` + "`" + `db:"updated_at" ` + "`" + `
	R postR ` + "`" + `db:"-" ` + "`" + `
}

type PostSlice []*Post
type postR struct{}
`

const postTagsModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import "github.com/gofrs/uuid/v5"

// PostTag is an object representing the database table.
// This table has a composite primary key — no pk tag on any single field.
type PostTag struct {
	PostID uuid.UUID ` + "`" + `db:"post_id" ` + "`" + `
	TagID  uuid.UUID ` + "`" + `db:"tag_id" ` + "`" + `
}

type PostTagSlice []*PostTag
`

const boilerplateModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models
// bob_joins — should be skipped
`

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

func TestParse_FindsTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if len(schema.Tables) != 2 {
		t.Errorf("got %d tables, want 2", len(schema.Tables))
	}
	if _, ok := schema.TableMap["users"]; !ok {
		t.Error("expected users table")
	}
	if _, ok := schema.TableMap["posts"]; !ok {
		t.Error("expected posts table")
	}
}

func TestParse_SkipsCompositePKTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "post_tags.bob.go", postTagsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if _, ok := schema.TableMap["post_tags"]; ok {
		t.Error("post_tags should be skipped — composite PK")
	}
	if len(schema.Tables) != 1 {
		t.Errorf("got %d tables, want 1", len(schema.Tables))
	}
}

func TestParse_SkipsExcludedTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	p.Exclude = []string{"posts"}

	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if _, ok := schema.TableMap["posts"]; ok {
		t.Error("posts should be excluded")
	}
	if len(schema.Tables) != 1 {
		t.Errorf("got %d tables, want 1", len(schema.Tables))
	}
}

func TestParse_ExtractsColumns(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]
	if users == nil {
		t.Fatal("users table not found")
	}

	if len(users.Columns) != 7 {
		t.Errorf("got %d columns, want 7", len(users.Columns))
	}

	// Primary key
	if users.PrimaryKey == nil {
		t.Fatal("PrimaryKey is nil")
	}
	if users.PrimaryKey.Name != "id" {
		t.Errorf("PrimaryKey.Name = %q, want id", users.PrimaryKey.Name)
	}

	// Nullable field
	bio := users.ColumnMap["bio"]
	if bio == nil {
		t.Fatal("bio column not found")
	}
	if !bio.Nullable {
		t.Error("bio should be nullable")
	}

	// Non-nullable field
	email := users.ColumnMap["email"]
	if email == nil {
		t.Fatal("email column not found")
	}
	if email.Nullable {
		t.Error("email should not be nullable")
	}
}

func TestParse_ResolvesGoTypes(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]

	cases := []struct {
		col          string
		wantTypeName string
		wantNullable bool
	}{
		{"id", "uuid.UUID", false},
		{"email", "string", false},
		{"bio", "string", true},
		{"created_at", "time.Time", false},
	}

	for _, c := range cases {
		col := users.ColumnMap[c.col]
		if col == nil {
			t.Errorf("column %q not found", c.col)
			continue
		}
		if col.GoType.Name != c.wantTypeName {
			t.Errorf("col %q GoType.Name = %q, want %q", c.col, col.GoType.Name, c.wantTypeName)
		}
		if col.Nullable != c.wantNullable {
			t.Errorf("col %q Nullable = %v, want %v", c.col, col.Nullable, c.wantNullable)
		}
	}
}

func TestParse_WiresForeignKeys(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	posts := schema.TableMap["posts"]
	if posts == nil {
		t.Fatal("posts table not found")
	}

	if len(posts.ForeignKeys) == 0 {
		t.Fatal("posts should have at least one FK")
	}

	fk := posts.ForeignKeys[0]
	if fk.TargetTable.Name != "users" {
		t.Errorf("FK target = %q, want users", fk.TargetTable.Name)
	}
	if fk.SourceColumn.Name != "user_id" {
		t.Errorf("FK source column = %q, want user_id", fk.SourceColumn.Name)
	}

	// users should have ReferencedBy
	users := schema.TableMap["users"]
	if len(users.ReferencedBy) == 0 {
		t.Error("users should be referenced by posts")
	}
}

func TestParse_NoFilesError(t *testing.T) {
	dir := t.TempDir()
	p := bob.New(dir, ir.DriverPostgres)
	_, err := p.Parse()
	if err == nil {
		t.Error("expected error for empty models dir, got nil")
	}
}

func TestParse_DriverIsPreserved(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverMySQL)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if schema.Driver != ir.DriverMySQL {
		t.Errorf("Driver = %q, want mysql", schema.Driver)
	}
}
