package bob_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/fisayoafolayan/kiln/internal/ir"
	"github.com/fisayoafolayan/kiln/internal/parser/bob"
)

// writeModel writes a bob-style .bob.go file to a temp dir.
func writeModel(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
		t.Fatalf("writing model file: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Fixtures — minimal bob-style model files
// ─────────────────────────────────────────────────────────────────────────────

const usersModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import (
	"time"
	"github.com/aarondl/opt/null"
	"github.com/gofrs/uuid/v5"
)

// User is an object representing the database table.
type User struct {
	ID        uuid.UUID        ` + "`" + `db:"id,pk" ` + "`" + `
	Email     string           ` + "`" + `db:"email" ` + "`" + `
	Name      string           ` + "`" + `db:"name" ` + "`" + `
	Bio       null.Val[string] ` + "`" + `db:"bio" ` + "`" + `
	Role      string           ` + "`" + `db:"role" ` + "`" + `
	CreatedAt time.Time        ` + "`" + `db:"created_at" ` + "`" + `
	UpdatedAt time.Time        ` + "`" + `db:"updated_at" ` + "`" + `
	R userR ` + "`" + `db:"-" ` + "`" + `
}

type UserSlice []*User
type userR struct{}
`

const postsModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import (
	"time"
	"github.com/aarondl/opt/null"
	"github.com/gofrs/uuid/v5"
)

// Post is an object representing the database table.
type Post struct {
	ID          uuid.UUID        ` + "`" + `db:"id,pk" ` + "`" + `
	UserID      uuid.UUID        ` + "`" + `db:"user_id" ` + "`" + `
	Title       string           ` + "`" + `db:"title" ` + "`" + `
	Body        string           ` + "`" + `db:"body" ` + "`" + `
	Status      string           ` + "`" + `db:"status" ` + "`" + `
	PublishedAt null.Val[time.Time] ` + "`" + `db:"published_at" ` + "`" + `
	CreatedAt   time.Time        ` + "`" + `db:"created_at" ` + "`" + `
	UpdatedAt   time.Time        ` + "`" + `db:"updated_at" ` + "`" + `
	R postR ` + "`" + `db:"-" ` + "`" + `
}

type PostSlice []*Post
type postR struct{
	User *User
}
`

const postTagsModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import "github.com/gofrs/uuid/v5"

// PostTag is an object representing the database table.
// This table has a composite primary key — no pk tag on any single field.
type PostTag struct {
	PostID uuid.UUID ` + "`" + `db:"post_id" ` + "`" + `
	TagID  uuid.UUID ` + "`" + `db:"tag_id" ` + "`" + `
}

type PostTagSlice []*PostTag
`

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

func TestParse_FindsTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if len(schema.Tables) != 2 {
		t.Errorf("got %d tables, want 2", len(schema.Tables))
	}
	if _, ok := schema.TableMap["users"]; !ok {
		t.Error("expected users table")
	}
	if _, ok := schema.TableMap["posts"]; !ok {
		t.Error("expected posts table")
	}
}

func TestParse_SkipsCompositePKTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "post_tags.bob.go", postTagsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if _, ok := schema.TableMap["post_tags"]; ok {
		t.Error("post_tags should be skipped — composite PK")
	}
	if len(schema.Tables) != 1 {
		t.Errorf("got %d tables, want 1", len(schema.Tables))
	}
}

func TestParse_SkipsExcludedTables(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	p.Exclude = []string{"posts"}

	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if _, ok := schema.TableMap["posts"]; ok {
		t.Error("posts should be excluded")
	}
	if len(schema.Tables) != 1 {
		t.Errorf("got %d tables, want 1", len(schema.Tables))
	}
}

func TestParse_ExtractsColumns(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]
	if users == nil {
		t.Fatal("users table not found")
	}

	if len(users.Columns) != 7 {
		t.Errorf("got %d columns, want 7", len(users.Columns))
	}

	// Primary key
	if users.PrimaryKey == nil {
		t.Fatal("PrimaryKey is nil")
	}
	if users.PrimaryKey.Name != "id" {
		t.Errorf("PrimaryKey.Name = %q, want id", users.PrimaryKey.Name)
	}

	// Nullable field
	bio := users.ColumnMap["bio"]
	if bio == nil {
		t.Fatal("bio column not found")
	}
	if !bio.Nullable {
		t.Error("bio should be nullable")
	}

	// Non-nullable field
	email := users.ColumnMap["email"]
	if email == nil {
		t.Fatal("email column not found")
	}
	if email.Nullable {
		t.Error("email should not be nullable")
	}
}

func TestParse_ResolvesGoTypes(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]

	cases := []struct {
		col          string
		wantTypeName string
		wantNullable bool
	}{
		{"id", "uuid.UUID", false},
		{"email", "string", false},
		{"bio", "string", true},
		{"created_at", "time.Time", false},
	}

	for _, c := range cases {
		col := users.ColumnMap[c.col]
		if col == nil {
			t.Errorf("column %q not found", c.col)
			continue
		}
		if col.GoType.Name != c.wantTypeName {
			t.Errorf("col %q GoType.Name = %q, want %q", c.col, col.GoType.Name, c.wantTypeName)
		}
		if col.Nullable != c.wantNullable {
			t.Errorf("col %q Nullable = %v, want %v", c.col, col.Nullable, c.wantNullable)
		}
	}
}

func TestParse_WiresForeignKeys(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "posts.bob.go", postsModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	posts := schema.TableMap["posts"]
	if posts == nil {
		t.Fatal("posts table not found")
	}

	if len(posts.ForeignKeys) == 0 {
		t.Fatal("posts should have at least one FK")
	}

	fk := posts.ForeignKeys[0]
	if fk.TargetTable.Name != "users" {
		t.Errorf("FK target = %q, want users", fk.TargetTable.Name)
	}
	if fk.SourceColumn.Name != "user_id" {
		t.Errorf("FK source column = %q, want user_id", fk.SourceColumn.Name)
	}

	// users should have ReferencedBy
	users := schema.TableMap["users"]
	if len(users.ReferencedBy) == 0 {
		t.Error("users should be referenced by posts")
	}
}

func TestParse_ExtractsEnumsFromDBInfo(t *testing.T) {
	// Create models dir inside a parent so dbinfo can be a sibling.
	parent := t.TempDir()
	modelsDir := filepath.Join(parent, "models")
	dbinfoDir := filepath.Join(parent, "dbinfo")
	os.MkdirAll(modelsDir, 0755)
	os.MkdirAll(dbinfoDir, 0755)

	writeModel(t, modelsDir, "users.bob.go", usersModel)

	// Write a dbinfo file with CHECK constraints containing enum values.
	dbinfoContent := `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package dbinfo

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{
		{constraint: constraint{Name: "users_role_check", Columns: []string{"role"}}, Expression: "((role)::text = ANY ((ARRAY['member'::text, 'moderator'::text, 'admin'::text])::text[]))"},
	}
}
`
	os.WriteFile(filepath.Join(dbinfoDir, "users.bob.go"), []byte(dbinfoContent), 0644)

	// Also need the bob_types file for it to be a valid dbinfo dir.
	typesContent := `package dbinfo

type check struct {
	constraint
	Expression string
}
type constraint struct {
	Name    string
	Columns []string
}
`
	os.WriteFile(filepath.Join(dbinfoDir, "bob_types.bob.go"), []byte(typesContent), 0644)

	p := bob.New(modelsDir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]
	if users == nil {
		t.Fatal("users table not found")
	}

	role := users.ColumnMap["role"]
	if role == nil {
		t.Fatal("role column not found")
	}
	if len(role.EnumValues) == 0 {
		t.Fatal("role.EnumValues should be populated from CHECK constraint")
	}
	want := []string{"member", "moderator", "admin"}
	if len(role.EnumValues) != len(want) {
		t.Fatalf("got %d enum values, want %d: %v", len(role.EnumValues), len(want), role.EnumValues)
	}
	for i, v := range want {
		if role.EnumValues[i] != v {
			t.Errorf("enum value [%d] = %q, want %q", i, role.EnumValues[i], v)
		}
	}
}

func TestParse_EnumConfigOverridesAutoDetection(t *testing.T) {
	// Same setup as above but we'll apply config override in the generator.
	// Here just verify auto-detection works — the generator test covers override.
	parent := t.TempDir()
	modelsDir := filepath.Join(parent, "models")
	dbinfoDir := filepath.Join(parent, "dbinfo")
	os.MkdirAll(modelsDir, 0755)
	os.MkdirAll(dbinfoDir, 0755)

	writeModel(t, modelsDir, "users.bob.go", usersModel)

	// Simple MySQL-style CHECK
	dbinfoContent := `package dbinfo

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{
		{constraint: constraint{Name: "users_role_check", Columns: []string{"role"}}, Expression: "(role IN ('member', 'admin'))"},
	}
}
`
	os.WriteFile(filepath.Join(dbinfoDir, "users.bob.go"), []byte(dbinfoContent), 0644)
	os.WriteFile(filepath.Join(dbinfoDir, "bob_types.bob.go"), []byte("package dbinfo\n"), 0644)

	p := bob.New(modelsDir, ir.DriverMySQL)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	role := schema.TableMap["users"].ColumnMap["role"]
	if len(role.EnumValues) != 2 {
		t.Fatalf("got %d enum values, want 2: %v", len(role.EnumValues), role.EnumValues)
	}
	if role.EnumValues[0] != "member" || role.EnumValues[1] != "admin" {
		t.Errorf("unexpected enum values: %v", role.EnumValues)
	}
}

func TestParse_ExtractsMaxLengthFromDBInfo(t *testing.T) {
	parent := t.TempDir()
	modelsDir := filepath.Join(parent, "models")
	dbinfoDir := filepath.Join(parent, "dbinfo")
	os.MkdirAll(modelsDir, 0755)
	os.MkdirAll(dbinfoDir, 0755)

	writeModel(t, modelsDir, "users.bob.go", usersModel)

	// Write a dbinfo file with varchar column types.
	dbinfoContent := `package dbinfo

var Users = Table{
	Name: "users",
	Columns: userColumns{
		Email: column{Name: "email", DBType: "varchar(255)"},
		Name:  column{Name: "name", DBType: "varchar(100)"},
		Role:  column{Name: "role", DBType: "varchar(50)"},
		Bio:   column{Name: "bio", DBType: "text"},
	},
}

type Table struct {
	Name    string
	Columns userColumns
}

type userColumns struct {
	Email column
	Name  column
	Role  column
	Bio   column
}

type column struct {
	Name   string
	DBType string
}
`
	os.WriteFile(filepath.Join(dbinfoDir, "users.bob.go"), []byte(dbinfoContent), 0644)
	os.WriteFile(filepath.Join(dbinfoDir, "bob_types.bob.go"), []byte("package dbinfo\n"), 0644)

	p := bob.New(modelsDir, ir.DriverMySQL)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	users := schema.TableMap["users"]
	if users == nil {
		t.Fatal("users table not found")
	}

	cases := []struct {
		col     string
		wantMax *int
	}{
		{"email", intPtr(255)},
		{"name", intPtr(100)},
		{"role", intPtr(50)},
		{"bio", nil}, // text has no max length
	}

	for _, c := range cases {
		col := users.ColumnMap[c.col]
		if col == nil {
			t.Errorf("column %q not found", c.col)
			continue
		}
		if c.wantMax == nil {
			if col.MaxLength != nil {
				t.Errorf("col %q MaxLength = %d, want nil", c.col, *col.MaxLength)
			}
		} else {
			if col.MaxLength == nil {
				t.Errorf("col %q MaxLength = nil, want %d", c.col, *c.wantMax)
			} else if *col.MaxLength != *c.wantMax {
				t.Errorf("col %q MaxLength = %d, want %d", c.col, *col.MaxLength, *c.wantMax)
			}
		}
	}
}

func intPtr(n int) *int { return &n }

func TestParse_ArrayTypes(t *testing.T) {
	dir := t.TempDir()

	// Model with Postgres array columns.
	arrayModel := `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import "github.com/gofrs/uuid/v5"

type Article struct {
	ID    uuid.UUID ` + "`" + `db:"id,pk" ` + "`" + `
	Title string    ` + "`" + `db:"title" ` + "`" + `
	Tags  []string  ` + "`" + `db:"tags" ` + "`" + `
	Scores []int64  ` + "`" + `db:"scores" ` + "`" + `
}
type ArticleSlice []*Article
`
	writeModel(t, dir, "articles.bob.go", arrayModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	articles := schema.TableMap["articles"]
	if articles == nil {
		t.Fatal("articles table not found")
	}

	tags := articles.ColumnMap["tags"]
	if tags == nil {
		t.Fatal("tags column not found")
	}
	if tags.GoType.Name != "[]string" {
		t.Errorf("tags GoType.Name = %q, want []string", tags.GoType.Name)
	}

	scores := articles.ColumnMap["scores"]
	if scores == nil {
		t.Fatal("scores column not found")
	}
	if scores.GoType.Name != "[]int64" {
		t.Errorf("scores GoType.Name = %q, want []int64", scores.GoType.Name)
	}
}

func TestParse_NoFilesError(t *testing.T) {
	dir := t.TempDir()
	p := bob.New(dir, ir.DriverPostgres)
	_, err := p.Parse()
	if err == nil {
		t.Error("expected error for empty models dir, got nil")
	}
}

func TestParse_DriverIsPreserved(t *testing.T) {
	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)

	p := bob.New(dir, ir.DriverMySQL)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	if schema.Driver != ir.DriverMySQL {
		t.Errorf("Driver = %q, want mysql", schema.Driver)
	}
}

// TestParse_RStructResolvesNonObviousFK verifies that the R struct
// correctly resolves FKs where the column name doesn't match the table name.
// e.g. articles.author_id → users (not "authors").
func TestParse_RStructResolvesNonObviousFK(t *testing.T) {
	// articles has author_id which points to users, not "authors".
	// Without R struct parsing, the _id heuristic would look for an "authors" table.
	const articlesModel = `// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
package models

import "github.com/gofrs/uuid/v5"

type Article struct {
	ID       uuid.UUID ` + "`" + `db:"id,pk" ` + "`" + `
	AuthorID uuid.UUID ` + "`" + `db:"author_id" ` + "`" + `
	Title    string    ` + "`" + `db:"title" ` + "`" + `
	R articleR ` + "`" + `db:"-" ` + "`" + `
}

type ArticleSlice []*Article
type articleR struct {
	Author *User
}
`

	dir := t.TempDir()
	writeModel(t, dir, "users.bob.go", usersModel)
	writeModel(t, dir, "articles.bob.go", articlesModel)

	p := bob.New(dir, ir.DriverPostgres)
	schema, err := p.Parse()
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}

	articles := schema.TableMap["articles"]
	if articles == nil {
		t.Fatal("articles table not found")
	}

	if len(articles.ForeignKeys) == 0 {
		t.Fatal("articles should have a FK to users via author_id")
	}

	fk := articles.ForeignKeys[0]
	if fk.SourceColumn.Name != "author_id" {
		t.Errorf("FK source column = %q, want author_id", fk.SourceColumn.Name)
	}
	if fk.TargetTable.Name != "users" {
		t.Errorf("FK target table = %q, want users", fk.TargetTable.Name)
	}

	// Verify users has the reverse reference
	users := schema.TableMap["users"]
	if len(users.ReferencedBy) == 0 {
		t.Error("users should be referenced by articles")
	}
}
